### ISSUE TITLE
Map list not loading on android

### ISSUE THREAD

**Issue by blobnom** [InventiveRhythm/fluXis#81]
### Type

Crash/Error/Exception

### Version

latest android ci build

### Description of the bug

I have 16 maps downloaded yet none of them show up in the song select screen's map list. They can be selected and played through for example the download maps screen but the map list never loads.

Device used: Samsung Galaxy S23 FE

Runtime Logs:
```----------------------------------------------------------
runtime Log (LogLevel: Verbose)
Running  0.0.0.0 on .NET 8.0.7
Environment: Android (Unix 34.0.0.0), 8 cores 
----------------------------------------------------------
2024-07-20 18:33:14 [verbose]: Initializing sentry client...
2024-07-20 18:33:14 [verbose]: 🖼️ Configuration renderer choice: Automatic
2024-07-20 18:33:14 [verbose]: 🖼️ Renderer fallback order: [ OpenGL ]
2024-07-20 18:33:14 [verbose]: 🖼️ Initialising "GL" renderer with "OpenGL" surface
2024-07-20 18:33:14 [verbose]: SDL3 Initialized
2024-07-20 18:33:14 [verbose]: SDL3 Version: 3.1.2
2024-07-20 18:33:14 [verbose]: SDL3 Revision:
2024-07-20 18:33:14 [verbose]: SDL application log [info]: pixel format wanted SDL_PIXELFORMAT_RGBA8888 (1), got SDL_PIXELFORMAT_RGBA8888 (1)
2024-07-20 18:33:14 [verbose]: SDL error log [debug]: That operation is not supported
2024-07-20 18:33:14 [verbose]: Updated display mode to desktop resolution: 1080x2340@120,00001, SDL_PIXELFORMAT_RGBA8888
2024-07-20 18:33:14 [verbose]: SDL error log [debug]: That operation is not supported
2024-07-20 18:33:14 [verbose]: SDL error log [debug]: That operation is not supported
2024-07-20 18:33:14 [verbose]: GL Initialized
2024-07-20 18:33:14 [verbose]: GL Version:                 OpenGL ES 3.2 ANGLE git hash: 72640fd9af5e
2024-07-20 18:33:14 [verbose]: GL Renderer:                ANGLE (Samsung Xclipse 920) on Vulkan 1.3.231
2024-07-20 18:33:14 [verbose]: GL Shader Language version: OpenGL ES GLSL ES 3.20 (ANGLE git hash: 72640fd9af5e)
2024-07-20 18:33:14 [verbose]: GL Vendor:                  Samsung Electronics Co., Ltd.
2024-07-20 18:33:14 [verbose]: GL Extensions:              GL_AMD_performance_monitor GL_ANDROID_extension_pack_es31a GL_ANGLE_base_vertex_base_instance GL_ANGLE_base_vertex_base_instance_shader_builtin GL_ANGLE_client_arrays GL_ANGLE_compressed_texture_etc GL_ANGLE_copy_texture_3d GL_ANGLE_depth_texture GL_ANGLE_framebuffer_blit GL_ANGLE_framebuffer_multisample GL_ANGLE_get_image GL_ANGLE_get_serialized_context_string GL_ANGLE_get_tex_level_parameter GL_ANGLE_instanced_arrays GL_ANGLE_memory_object_flags GL_ANGLE_memory_size GL_ANGLE_multi_draw GL_ANGLE_program_cache_control GL_ANGLE_read_only_depth_stencil_feedback_loops GL_ANGLE_relaxed_vertex_attribute_type GL_ANGLE_request_extension GL_ANGLE_robust_client_memory GL_ANGLE_robust_fragment_shader_output GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ANGLE_texture_multisample GL_ANGLE_texture_usage GL_ANGLE_vulkan_image GL_ANGLE_yuv_internal_format GL_APPLE_clip_distance GL_CHROMIUM_bind_generates_resource GL_CHROMIUM_bind_uniform_location GL_CHROMIUM_copy_compressed_texture GL_CHROMIUM_copy_texture GL_CHROMIUM_lose_context GL_EXT_EGL_image_array GL_EXT_EGL_image_external_wrap_modes GL_EXT_YUV_target GL_EXT_base_instance GL_EXT_blend_func_extended GL_EXT_blend_minmax GL_EXT_buffer_storage GL_EXT_clip_control GL_EXT_clip_cull_distance GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_EXT_compressed_ETC1_RGB8_sub_texture GL_EXT_copy_image GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_disjoint_timer_query GL_EXT_draw_buffers GL_EXT_draw_buffers_indexed GL_EXT_draw_elements_base_vertex GL_EXT_external_buffer GL_EXT_float_blend GL_EXT_frag_depth GL_EXT_geometry_shader GL_EXT_gpu_shader5 GL_EXT_instanced_arrays GL_EXT_map_buffer_range GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_multi_draw_indirect GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_EXT_occlusion_query_boolean GL_EXT_primitive_bounding_box GL_EXT_protected_textures GL_EXT_read_format_bgra GL_EXT_robustness GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_semaphore GL_EXT_semaphore_fd GL_EXT_shader_io_blocks GL_EXT_shader_non_constant_global_initializers GL_EXT_shader_texture_lod GL_EXT_shadow_samplers GL_EXT_tessellation_shader GL_EXT_texture_border_clamp GL_EXT_texture_buffer GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_s3tc_srgb GL_EXT_texture_cube_map_array GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_texture_format_sRGB_override GL_EXT_texture_rg GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_EXT_texture_sRGB_decode GL_EXT_texture_storage GL_EXT_texture_type_2_10_10_10_REV GL_EXT_unpack_subimage GL_KHR_blend_equation_advanced GL_KHR_debug GL_KHR_robust_buffer_access_behavior GL_KHR_texture_compression_astc_ldr GL_NV_depth_buffer_float2 GL_NV_fence GL_NV_framebuffer_blit GL_NV_pack_subimage GL_NV_pixel_buffer_object GL_NV_read_depth GL_NV_read_depth_stencil GL_NV_read_stencil GL_NV_shader_noperspective_interpolation GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_compressed_EAC_R11_signed_texture GL_OES_compressed_EAC_R11_unsigned_texture GL_OES_compressed_EAC_RG11_signed_texture GL_OES_compressed_EAC_RG11_unsigned_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_compressed_ETC2_RGB8_texture GL_OES_compressed_ETC2_RGBA8_texture GL_OES_compressed_ETC2_punchthroughA_RGBA8_texture GL_OES_compressed_ETC2_punchthroughA_sRGB8_alpha_texture GL_OES_compressed_ETC2_sRGB8_alpha8_texture GL_OES_compressed_ETC2_sRGB8_texture GL_OES_depth24 GL_OES_depth32 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_draw_buffers_indexed GL_OES_draw_elements_base_vertex GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_geometry_shader GL_OES_get_program_binary GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_primitive_bounding_box GL_OES_rgb8_rgba8 GL_OES_sample_shading GL_OES_sample_variables GL_OES_shader_image_atomic GL_OES_shader_io_blocks GL_OES_shader_multisample_interpolation GL_OES_standard_derivatives GL_OES_surfaceless_context GL_OES_texture_3D GL_OES_texture_border_clamp GL_OES_texture_buffer GL_OES_texture_cube_map_array GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_texture_stencil8 GL_OES_texture_storage_multisample_2d_array GL_OES_vertex_array_object GL_OES_vertex_half_float GL_OES_vertex_type_10_10_10_2 GL_OVR_multiview GL_OVR_multiview2 GL_QCOM_shading_rate
2024-07-20 18:33:14 [verbose]: UseStructuredBuffers: False
2024-07-20 18:33:14 [verbose]: 🖼️ Renderer initialised!
2024-07-20 18:33:14 [verbose]: Host execution state changed to Running
2024-07-20 18:33:14 [verbose]: Execution mode changed to SingleThread
2024-07-20 18:33:15 [verbose]: Failed to get fullscreen display mode. Display index: 0. SDL error: That operation is not supported
2024-07-20 18:33:15 [verbose]: 🔈 BASS initialised
2024-07-20 18:33:15 [verbose]: BASS version:           2.4.16.7
2024-07-20 18:33:15 [verbose]: BASS FX version:        2.4.12.6
2024-07-20 18:33:15 [verbose]: BASS MIX version:       2.4.11.1
2024-07-20 18:33:15 [verbose]: Device:                 Default
2024-07-20 18:33:15 [verbose]: Driver:
2024-07-20 18:33:15 [verbose]: Update period:          5 ms
2024-07-20 18:33:15 [verbose]: Device buffer length:   10 ms
2024-07-20 18:33:15 [verbose]: Playback buffer length: 100 ms
2024-07-20 18:33:15 [verbose]: 🔈 BASS initialised
2024-07-20 18:33:15 [verbose]: BASS version:           2.4.16.7
2024-07-20 18:33:15 [verbose]: BASS FX version:        2.4.12.6
2024-07-20 18:33:15 [verbose]: BASS MIX version:       2.4.11.1
2024-07-20 18:33:15 [verbose]: Device:                 Default
2024-07-20 18:33:15 [verbose]: Driver:
2024-07-20 18:33:15 [verbose]: Update period:          5 ms
2024-07-20 18:33:15 [verbose]: Device buffer length:   10 ms
2024-07-20 18:33:15 [verbose]: Playback buffer length: 100 ms
2024-07-20 18:33:15 [verbose]: 📺 FluXisScreenStack#242(depth:1) scheduling push LoadingScreen#101
2024-07-20 18:33:15 [verbose]: Texture -'s upload queue is large (100)
2024-07-20 18:33:15 [verbose]: Texture -'s upload queue is large (200)
2024-07-20 18:33:15 [verbose]: SDL error log [debug]: That operation is not supported
2024-07-20 18:33:15 [verbose]: Loading maps...
2024-07-20 18:33:15 [verbose]: Found 16 maps
2024-07-20 18:33:16 [verbose]: Loaded 0 plugins
2024-07-20 18:33:16 [verbose]: Loaded 0 importers
2024-07-20 18:33:16 [error]: Failed to load layout ce937f1a-619e-45ae-849c-9c11ccdeb676.json
2024-07-20 18:33:16 [verbose]: 📺 FluXisScreenStack#242(depth:1) entered LoadingScreen#101
2024-07-20 18:33:16 [verbose]: Texture 4's upload queue is large (100)
2024-07-20 18:33:17 [verbose]: 📺 FluXisScreenStack#242(depth:1) suspended LoadingScreen#101 (waiting on WarningScreen#994)
2024-07-20 18:33:17 [verbose]: 📺 FluXisScreenStack#242(depth:2) loading WarningScreen#994
2024-07-20 18:33:17 [verbose]: 📺 FluXisScreenStack#242(depth:2) entered WarningScreen#994
2024-07-20 18:33:30 [verbose]: 📺 FluXisScreenStack#242(depth:2) suspended WarningScreen#994 (waiting on IntroAnimation#-19)
2024-07-20 18:33:30 [verbose]: 📺 FluXisScreenStack#242(depth:3) loading IntroAnimation#-19
2024-07-20 18:33:30 [verbose]: 📺 FluXisScreenStack#242(depth:3) entered IntroAnimation#-19
2024-07-20 18:33:32 [verbose]: 📺 FluXisScreenStack#242(depth:3) suspended IntroAnimation#-19 (waiting on MenuScreen#197)
2024-07-20 18:33:32 [verbose]: 📺 FluXisScreenStack#242(depth:4) entered MenuScreen#197
2024-07-20 18:33:35 [verbose]: fluXis.Game.Online.Fluxel.FluxelClient
2024-07-20 18:33:51 [verbose]: 📺 FluXisScreenStack#242(depth:4) suspended MenuScreen#197 (waiting on SelectScreen#631)
2024-07-20 18:33:51 [verbose]: 📺 FluXisScreenStack#242(depth:5) loading SelectScreen#631
2024-07-20 18:33:52 [verbose]: 📺 FluXisScreenStack#242(depth:5) entered SelectScreen#631
2024-07-20 18:33:56 [verbose]: 📺 FluXisScreenStack#242(depth:4) exit from SelectScreen#631
2024-07-20 18:33:56 [verbose]: 📺 FluXisScreenStack#242(depth:4) resume to MenuScreen#197
2024-07-20 18:33:58 [error]: An unobserved error has occurred.
2024-07-20 18:33:58 [error]: System.InvalidOperationException: NullabilityInfoContext_NotSupported
2024-07-20 18:33:58 [error]: at System.Reflection.NullabilityInfoContext.Create(PropertyInfo )
2024-07-20 18:33:58 [error]: at osu.Framework.Extensions.TypeExtensions.TypeExtensions.IsNullable(PropertyInfo propertyInfo)
2024-07-20 18:33:58 [error]: at osu.Framework.Allocation.ResolvedAttribute.CreateActivator(Type type)
2024-07-20 18:33:58 [error]: at osu.Framework.Allocation.DependencyActivator..ctor(Type type)
2024-07-20 18:33:58 [error]: at osu.Framework.Allocation.DependencyActivator.getActivator(Type type)
2024-07-20 18:33:58 [error]: at osu.Framework.Allocation.DependencyActivator.<MergeDependencies>g__mergeRecursively|9_0[CompositeDrawable](Object obj, IReadOnlyDependencyContainer dependencies, CacheInfo info, Type currentType)
2024-07-20 18:33:58 [error]: at osu.Framework.Allocation.DependencyActivator.MergeDependencies[CompositeDrawable](CompositeDrawable obj, IReadOnlyDependencyContainer dependencies, CacheInfo info)
2024-07-20 18:33:58 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.CreateChildDependencies(IReadOnlyDependencyContainer parent)
2024-07-20 18:33:58 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2024-07-20 18:33:58 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2024-07-20 18:33:58 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2024-07-20 18:33:58 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadChild(Drawable child)
2024-07-20 18:33:58 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.AddInternal(Drawable drawable)
2024-07-20 18:33:58 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.AddRangeInternal(IEnumerable`1 range)
2024-07-20 18:33:58 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.set_InternalChildrenEnumerable(IEnumerable`1 value)
2024-07-20 18:33:58 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.set_InternalChildren(IReadOnlyList`1 value)
2024-07-20 18:33:58 [error]: at fluXis.Game.Screens.Select.List.MapListEntry.load()
2024-07-20 18:33:58 [error]: at fluXis.Game.Screens.Select.List.MapListEntry.<>c.<RegisterForDependencyActivation>b__33_0(Object t, IReadOnlyDependencyContainer d)
2024-07-20 18:33:58 [error]: at osu.Framework.Allocation.DependencyActivator.<Activate>g__activateRecursively|8_0[Drawable](Object obj, IReadOnlyDependencyContainer dependencies, Type currentType)
2024-07-20 18:33:58 [error]: at osu.Framework.Allocation.DependencyActivator.Activate[Drawable](Drawable obj, IReadOnlyDependencyContainer dependencies)
2024-07-20 18:33:58 [error]: at osu.Framework.Allocation.DependencyContainer.Inject[Drawable](Drawable instance)
2024-07-20 18:33:58 [error]: at osu.Framework.Graphics.Drawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2024-07-20 18:33:58 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.InjectDependencies(IReadOnlyDependencyContainer dependencies)
2024-07-20 18:33:58 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2024-07-20 18:33:58 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2024-07-20 18:33:58 [error]: at osu.Framework.Graphics.Drawable.LoadFromAsync(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2024-07-20 18:33:58 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadComponents[MapListEntry](List`1 components, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext, CancellationToken cancellation)
2024-07-20 18:33:58 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.LoadComponents[MapListEntry](IEnumerable`1 components)
2024-07-20 18:33:58 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.LoadComponent[MapListEntry](MapListEntry component)
2024-07-20 18:33:58 [error]: at fluXis.Game.Screens.Select.SelectScreen.loadMapSets()
2024-07-20 18:33:58 [error]: at fluXis.Game.Screens.Select.SelectScreen.<LoadComplete>b__77_0()
2024-07-20 18:33:58 [error]: at System.Threading.Tasks.Task.InnerInvoke()
2024-07-20 18:33:58 [error]: at System.Threading.Tasks.Task.<>c.<.cctor>b__281_0(Object obj)
2024-07-20 18:33:58 [error]: at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread , ExecutionContext , ContextCallback , Object )
2024-07-20 18:33:58 [error]: --- End of stack trace from previous location ---
2024-07-20 18:33:58 [error]: at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread , ExecutionContext , ContextCallback , Object )
2024-07-20 18:33:58 [error]: at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& , Thread )
2024-07-20 18:34:03 [verbose]: SDL error log [debug]: no current context
2024-07-20 18:35:55 [verbose]: SDL application log [info]: pixel format wanted SDL_PIXELFORMAT_RGBA8888 (1), got SDL_PIXELFORMAT_RGBA8888 (1)
2024-07-20 18:35:55 [verbose]: Execution mode changed to SingleThread
2024-07-20 18:36:43 [verbose]: SDL error log [debug]: no current context
```

### Screenshots/Video

![Screenshot_20240720_203825](https://github.com/user-attachments/assets/3e3e224c-9df0-4a54-b585-bd3bb593d8d0)
![Screenshot_20240720_203757](https://github.com/user-attachments/assets/5f7a50b5-b011-486f-bd0f-4702b3cf1d9c)
![Screenshot_20240720_205023](https://github.com/user-attachments/assets/dcaa331f-907b-46a3-ab66-bc5d8fc6436f)

**Comment by flustix** [comment]
Android support is very much not intended for the public right now. And I honestly don't even know if it will ever be done properly because the game isn't really that playable on mobile devices.

**Comment by blobnom** [comment]
Understandable
